name: dart_libs
description: >
  Lab to practice with Dart libraries
environment:
  sdk: '^3.5.0'
dependencies:
  http: ^1.2.2
  intl: ^0.19.0
  path: ^1.9.0
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
